export enum TableType {
  MERCH = "MERCH",
  AIRDROP = "AIRDROP",
  LOOTBOX = "LOOTBOX",
  CLAIMABLELOOTBOX = "CLAIMABLELOOTBOX",
  MINT = "MINT",
  BURN = "BURN",
  CANCEL = "CANCEL",
  COLLECTION = "COLLECTION",
  ERC1155LOOTBOX = "ERC1155LOOTBOX",
  ERC1155SCULPTURE = "ERC1155SCULPTURE",
}
