# Use postgres/example user/password credentials
version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: loyalty_sipher
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 15432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    command: ["sh", "-c", 'exec redis-server --requirepass "12345678"']
    volumes:
      - ./redis/data:/data
    ports:
      - 16379:6379
