export const erc721Abi = [
  "event Approval(address indexed owner, address indexed approved, uint256 indexed tokenID)",
  "event ApprovalForAll(address indexed owner, address indexed operator, bool approved)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenID)",
  "function approve(address to, uint256 tokenID)",
  "function balanceOf(address owner) view returns (uint256)",
  "function getApproved(uint256 tokenID) view returns (address)",
  "function isApprovedForAll(address owner, address operator) view returns (bool)",
  "function ownerOf(uint256 tokenID) view returns (address)",
  "function safeTransferFrom(address from, address to, uint256 tokenID)",
  "function safeTransferFrom(address from, address to, uint256 tokenID, bytes _data)",
  "function setApprovalForAll(address operator, bool approved)",
  "function tokenURI(uint256 tokenID) view returns (string)",
  "function transferFrom(address from, address to, uint256 tokenID)",
  "function symbol() view returns (string)",
  "function name() view returns (string)",
];
