name: CI workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branchs
  push:
    branches: [develop, staging, main]
    paths-ignore:
      - ".github/**"
  pull_request:
    branches: [develop, staging, main]
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

jobs:
  #-------------Workflow---------------
  # 1. Check PR: Unit test, build
  # 2. Merged: Build, Update manifest k8s
  # 3. Run Terraform for frontend
  #------------------------------------

  # Check branch
  check_module_changed:
    #if: ${{ (github.ref_name == 'dev' || github.ref_name == 'develop') }}
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            backend: ./**

  # Terraform for frontend
  terraform-plan-for-dev:
    if: github.base_ref == 'develop'
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: NPM Setup
        run: |
          cat << EOF >> .npmrc
          always-auth=true
          //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF

      - name: Yarn install
        run: yarn install

      - name: Build packages
        run: cd packages/frontend && yarn build:tf

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd packages/frontend && terraform init -var='region=us-west-2' -var='cloudfront_aliases=${{ secrets.CLOUDFRONT_ALIAS_DEV }}' -var='cloudfront_acm_certificate_arn=${{ secrets.CLOUDFRONT_ACM_CERT_ARN_DEV }}' -backend-config='bucket=${{ secrets.STATE_BUCKET_DEV }}' -backend-config='region=${{secrets.NONPROD_TF_AWS_REGION}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        run: cd packages/frontend && terraform validate

      - name: Terraform Plan
        run: |
          cd packages/frontend && terraform plan -var='region=us-west-2' -var='cloudfront_aliases=${{ secrets.CLOUDFRONT_ALIAS_DEV }}' -var='cloudfront_acm_certificate_arn=${{ secrets.CLOUDFRONT_ACM_CERT_ARN_DEV }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

      - name: Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: ""
          fields: repo,message,commit,author,eventName,ref,workflow,job,pullRequest
        if: always() # Pick up events even if the job fails or is canceled.

  terraform-apply-for-dev:
    if: github.ref_name == 'develop'
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: NPM Setup
        run: |
          cat << EOF >> .npmrc      
          always-auth=true
          //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF

      - name: Yarn install
        run: yarn install

      - name: Build packages
        run: cd packages/frontend && yarn build:tf
        env:
          NEXT_PUBLIC_DASHBOARD_FE_URL: "https://loyalty.sipher.gg/"
          NEXT_PUBLIC_DASHBOARD_URL: "https://api-loyalty.sipher.gg/"
          NEXT_PUBLIC_ATHER_ID_URL: "https://api-atherid.sipher.gg"
          NEXT_PUBLIC_ATHER_SOCIAL_URL: "https://api-ather-social.sipher.gg/api"
          NEXT_PUBLIC_SC_SCULPTURE: "0x3EdB954303D0A13ee347C6989189294B0422E7D6"
          NEXT_PUBLIC_SC_LOOTBOX: "0x3E445D426c8FdE12F5F0C223019CA9158f7Da93B"
          NEXT_PUBLIC_SC_INU: "0x4d91fa57abfead5fbc8445e45b906b85bbd9744c"
          NEXT_PUBLIC_SC_NEKO: "0x97c8480d593b93ae90f8613a5b2ac02e7a3dd0ed"
          NEXT_PUBLIC_POLYGON_CHAIN: "80001"

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd packages/frontend && terraform init -var='region=us-west-2' -var='cloudfront_aliases=${{ secrets.CLOUDFRONT_ALIAS_DEV }}' -var='cloudfront_acm_certificate_arn=${{ secrets.CLOUDFRONT_ACM_CERT_ARN_DEV }}' -backend-config='bucket=${{ secrets.STATE_BUCKET_DEV }}' --backend-config='region=${{secrets.NONPROD_TF_AWS_REGION}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        run: cd packages/frontend && terraform validate

      - name: Terraform Apply
        run: |
          cd packages/frontend && terraform apply -auto-approve -var='region=us-west-2' -var='cloudfront_aliases=${{ secrets.CLOUDFRONT_ALIAS_DEV }}' -var='cloudfront_acm_certificate_arn=${{ secrets.CLOUDFRONT_ACM_CERT_ARN_DEV }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

      - name: Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: ""
          fields: repo,message,commit,author,eventName,ref,workflow,job,pullRequest
        if: always() # Pick up events even if the job fails or is canceled.

  #------------Dev branch------------------
  # When creating PR to develop branch
  backend-pre-merged-dev:
    needs: check_module_changed
    if: ${{ github.base_ref == 'develop' && needs.check_module_changed.outputs.backend == 'true'}}
    uses: sipherxyz/sipher-loyalty/.github/workflows/default-check-pr.yml@template
    with:
      module: backend
    secrets:
      webhook: ${{ secrets.SLACK_WEBHOOK_URL }}

  # When code merged to develop branch
  backend-post-merged-dev:
    needs: check_module_changed
    if: ${{ github.ref_name == 'develop' && needs.check_module_changed.outputs.backend == 'true'}}
    uses: sipherxyz/sipher-loyalty/.github/workflows/default-build_deploy.yml@template
    with:
      module: backend
      aws_region: us-east-1
      argocd_host: cd-dev.sipher.gg
      argocd_user: admin
    secrets:
      aws_accesskey: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }} # plaintext in github secret
      aws_secret: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }} # plaintext in github secret
      webhook: ${{ secrets.SLACK_WEBHOOK_URL }} # plaintext in github secret
      argocd_secret: ${{ secrets.DEV_ARGOCD_SECRET }} # plaintext in github secret
  #-----------------------------------

  #------------Main branch------------------
  # When creating PR to main branch
  backend-pre-merged-main:
    needs: check_module_changed
    if: ${{ github.base_ref == 'main' && needs.check_module_changed.outputs.backend == 'true'}}
    uses: sipherxyz/sipher-loyalty/.github/workflows/default-check-pr.yml@template
    with:
      module: backend
    secrets:
      webhook: ${{ secrets.SLACK_WEBHOOK_URL }}

  # When code merged to main branch
  backend-post-merged-main:
    needs: check_module_changed
    if: ${{ github.ref_name == 'main' && needs.check_module_changed.outputs.backend == 'true'}}
    uses: sipherxyz/sipher-loyalty/.github/workflows/default-build_deploy.yml@template
    with:
      module: backend
      aws_region: ap-southeast-1
      argocd_host: argocd01.sipher.gg
      argocd_user: admin
    secrets:
      aws_accesskey: ${{ secrets.AWS_WEB_ACCESS_KEY_ID }} # plaintext in github secret
      aws_secret: ${{ secrets.AWS_WEB_SECRET_ACCESS_KEY }} # plaintext in github secret
      webhook: ${{ secrets.SLACK_WEBHOOK_URL }} # plaintext in github secret
      argocd_secret: ${{ secrets.ARGOCD_SECRET }} # plaintext in github secret
  #-----------------------------------

  terraform-plan-for-prod:
    if: github.base_ref == 'main'
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: NPM Setup
        run: |
          cat << EOF >> .npmrc      
          always-auth=true
          //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF

      - name: Yarn install
        run: yarn install

      - name: Build packages
        run: cd packages/frontend && yarn build:tf

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd packages/frontend && terraform init -var='region=${{secrets.PROD_TF_AWS_REGION}}' -var='cloudfront_aliases=${{ secrets.CLOUDFRONT_ALIAS_PROD }}' -var='cloudfront_acm_certificate_arn=${{ secrets.CLOUDFRONT_ACM_CERT_ARN_PROD }}' -backend-config='bucket=${{ secrets.STATE_BUCKET_PROD }}' -backend-config='region=${{secrets.PROD_TF_AWS_REGION}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_WEB_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_WEB_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        run: cd packages/frontend && terraform validate

      - name: Terraform Plan
        run: |
          cd packages/frontend && terraform plan -var='region=${{secrets.PROD_TF_AWS_REGION}}' -var='cloudfront_aliases=${{ secrets.CLOUDFRONT_ALIAS_PROD }}' -var='cloudfront_acm_certificate_arn=${{ secrets.CLOUDFRONT_ACM_CERT_ARN_PROD }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_WEB_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_WEB_SECRET_ACCESS_KEY }}

      - name: Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: ""
          fields: repo,message,commit,author,eventName,ref,workflow,job,pullRequest
        if: always() # Pick up events even if the job fails or is canceled.

  terraform-apply-for-prod:
    if: github.ref_name == 'main'
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: NPM Setup
        run: |
          cat << EOF >> .npmrc      
          always-auth=true
          //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF

      - name: Yarn install
        run: yarn install

      - name: Build packages
        run: cd packages/frontend && yarn build:tf
        env:
          NEXT_PUBLIC_DASHBOARD_FE_URL: https://dashboard.sipher.gg/signin
          NEXT_PUBLIC_DASHBOARD_URL: https://api-dashboard.atherlabs.xyz/
          NEXT_PUBLIC_ATHER_ID_URL: https://api-atherid.atherlabs.xyz
          NEXT_PUBLIC_ATHER_SOCIAL_URL: https://api-ather-social.atherlabs.xyz/api
          NEXT_PUBLIC_SC_SCULPTURE: "0x04c20C117F7F470620F45a1c685f50ef1516a958"
          NEXT_PUBLIC_SC_LOOTBOX: "0x105c1fDa04c7406D4106C96bc5b674f7d6B1A617"
          NEXT_PUBLIC_SC_INU: "0x9c57D0278199c931Cf149cc769f37Bb7847091e7"
          NEXT_PUBLIC_SC_NEKO: "0x09E0dF4aE51111CA27d6B85708CFB3f1F7cAE982"
          NEXT_PUBLIC_POLYGON_CHAIN: "137"

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          cd packages/frontend && terraform init -var='region=${{secrets.PROD_TF_AWS_REGION}}' -var='cloudfront_aliases=${{ secrets.CLOUDFRONT_ALIAS_PROD }}' -var='cloudfront_acm_certificate_arn=${{ secrets.CLOUDFRONT_ACM_CERT_ARN_PROD }}' -backend-config='bucket=${{ secrets.STATE_BUCKET_PROD }}' -backend-config='region=${{secrets.PROD_TF_AWS_REGION}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_WEB_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_WEB_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        run: cd packages/frontend && terraform validate

      - name: Terraform Apply
        run: |
          cd packages/frontend && terraform apply -auto-approve -var='region=${{secrets.PROD_TF_AWS_REGION}}' -var='cloudfront_aliases=${{ secrets.CLOUDFRONT_ALIAS_PROD }}' -var='cloudfront_acm_certificate_arn=${{ secrets.CLOUDFRONT_ACM_CERT_ARN_PROD }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_WEB_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_WEB_SECRET_ACCESS_KEY }}

      - name: Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: ""
          fields: repo,message,commit,author,eventName,ref,workflow,job,pullRequest
        if: always() # Pick up events even if the job fails or is canceled.
